{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount }}
  labels:
    app: {{ .Release.Name }}-selenoid
    release: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name:  {{ .Values.rbac.serviceAccount }}
  labels:
    app: {{ .Release.Name }}-selenoid
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ .Values.rbac.serviceAccount }}
  labels:
    app: {{ .Release.Name }}-selenoid
    release: {{ .Release.Name }}
roleRef:
  kind: Role
  name:  {{ .Values.rbac.serviceAccount }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name:  {{ .Values.rbac.serviceAccount }}
{{- end }}
