apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-selenoid
  labels:
    app: {{ .Release.Name }}-selenoid
    release: {{ .Release.Name }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: selenoid-ui
    {{- if ( and ( .Values.service.nodePortUi ) ( eq .Values.service.type "NodePort" ) ) }}
    nodePort: {{.Values.service.nodePortUi}}
    {{- end }}
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: selenoidk8s-hub
    {{- if ( and ( .Values.service.nodePortHub ) ( eq .Values.service.type "NodePort" ) ) }}
    nodePort: {{.Values.service.nodePortHub}}
    {{- end }}
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    name: {{ .Release.Name }}-selenoid
  sessionAffinity: None
  type: {{ .Values.service.type }}
